export const videoData = [
  {
    id: 1,
    youtubeLink: "https://youtu.be/LouAyR7pcIc?si=vRwBA-4hvSM_0sA-",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Andhera_Ujala_Title_Screen.png/220px-Andhera_Ujala_Title_Screen.png",
    dramaName: "Andhera Ujhala",
    year: 1995,
    actor: "Ali Raza",
    producer: "Saira Bano",
    director: "Kamal Ahmed",
    writer: "Fatima Jinnah",
  },
  {
    id: 2,
    youtubeLink: "https://youtu.be/aKXdT2N7xTI?si=TBDbYqb8rHp8fi7v",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Dil-e-Nadaan.jpg/250px-Dil-e-Nadaan.jpg",
    dramaName: "Dil-e-Nastaan",
    year: 1998,
    actor: "Ahmed Ali",
    producer: "Shazia Khalid",
    director: "Waleed Malik",
    writer: "Rizwan Ahmed",
  },
  {
    id: 3,
    youtubeLink: "https://youtu.be/k6izno1NFd8?si=RCu5VeMxSJ8pzvd3",
    thumbnail: "https://upload.wikimedia.org/wikipedia/en/6/65/RangMahal.jpeg",
    dramaName: "Rang Mahal",
    year: 2001,
    actor: "Hina Khan",
    producer: "Saima Noor",
    director: "Shoaib Mansoor",
    writer: "Sadia Sheikh",
  },
  {
    id: 4,
    youtubeLink: "https://youtu.be/4x932mV1tkc?si=Q0BgIRGgWxaXezFB",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/2/2a/Zindagi_Gulzar_hai_title_screen.jpg?20250104000437",
    dramaName: "Zindagi Gulzar Hai",
    year: 2012,
    actor: "Fawad Khan",
    producer: "Momina Duraid",
    director: "Sohail Khan",
    writer: "Umera Ahmed",
  },
  {
    id: 5,
    youtubeLink: "https://youtu.be/3GA5XA3t60k?si=MwB5nRkCvIiPGVTz",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Title_Screen_of_Hum_TV%27s_Udaari.jpg/330px-Title_Screen_of_Hum_TV%27s_Udaari.jpg",
    dramaName: "Udaari",
    year: 2016,
    actor: "Urwa Hocane",
    producer: "Shahid Productions",
    director: "Mehreen Jabbar",
    writer: "Bilal Ashraf",
  },
  {
    id: 6,
    youtubeLink: "https://youtu.be/iQYGN1_4p08?si=R5jglbvsvk4sIKor",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Humsafar.png/270px-Humsafar.png",
    dramaName: "Humsafar",
    year: 2011,
    actor: "Mahira Khan",
    producer: "Momina Duraid",
    director: "Shoaib Mansoor",
    writer: "Farhat Ishtiaq",
  },
  {
    id: 7,
    youtubeLink: "https://youtu.be/ML0CxZzkdJ4?si=tkEWNO9Hkm5bygHi",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Shehr-e-Zaat_Hum_TV.jpg/250px-Shehr-e-Zaat_Hum_TV.jpg",
    dramaName: "Shehr-e-Zaat",
    year: 2012,
    actor: "Mahira Khan",
    producer: "Momina Duraid",
    director: "Shoaib Mansoor",
    writer: "Umera Ahmed",
  },
  {
    id: 8,
    youtubeLink: "https://youtu.be/UNudu7jrC3I?si=g0lOBoRWsvwX_mts",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/thumb/4/44/ZaraYaadKar.jpg/220px-ZaraYaadKar.jpg",
    dramaName: "Zara Yaad Kar",
    year: 1999,
    actor: "Moammar Rana",
    producer: "Saira Durrani",
    director: "Anwar Maqsood",
    writer: "Imran Nazir",
  },
  {
    id: 9,
    youtubeLink: "https://youtu.be/d6gi_AXQQ9Y?si=gY9aLm-2iTTkNnES",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/thumb/7/7d/Angan_tehra_opening_credit.jpg/250px-Angan_tehra_opening_credit.jpg",
    dramaName: "Aangan Terha",
    year: 1984,
    actor: "Bushra Ansari",
    producer: "Satish Anand",
    director: "Faisal Qureshi",
    writer: "Anwar Maqsood",
  },
  {
    id: 10,
    youtubeLink: "https://youtu.be/CxcRDfizYzY?si=vqsrDJML4OHmFC4a",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Hum_TV_drama_Dastaan_by_Haissam_Hussain.jpg/250px-Hum_TV_drama_Dastaan_by_Haissam_Hussain.jpg",
    dramaName: "Dastaan",
    year: 2010,
    actor: "Sanam Baloch",
    producer: "Hum TV",
    director: "Babar Javed",
    writer: "Noor ul Huda Shah",
  },
];
